### ISSUE TITLE
Implement timedelta for CLI

### ISSUE THREAD

**Issue by sPredictorX1708** [dubesar/worldtimebuddy#1]
This will add a new feature to this which can be used like 

`worldtimebuddy --timezone UTC --delta +2hr`

The above command should return +2hrs in UTC timezone. Be careful this should only work if timezone flag is available.

Sample combinations

```
worldtimebuddy --timezone UTC --delta -2hr
worldtimebuddy --timezone UTC --delta -2min
worldtimebuddy --timezone UTC --delta +2min
worldtimebuddy --timezone UTC --delta -1day
```

**Comment by bakayu** [comment]
Hey! I would like to work on this, please assign the issue to me ^^
